version: '3'
services:
    rasa:
      container_name: "rasa_server_cartera2"
      user: root
      build: 
        context:  .
      volumes:
      - "./:/app"
      ports: 
        - "5011:5005"
    action_server:
      container_name: "action_server_cartera2"
      build: 
        context: actions
      volumes:
        - ./actions:/app/actions
        - ./data:/app/data
      ports:
        - 5061:5055
